# Generated by Django 4.1.5 on 2023-01-20 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_remove_author_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='grad_year',
            field=models.IntegerField(default=26, verbose_name='class'),
        ),
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(default='polls/pp.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='quote',
            name='quoted',
            field=models.DateTimeField(null=True, verbose_name='date quoted'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
